-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 08:17:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema SensorInfo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SensorInfo` ;

-- -----------------------------------------------------
-- Schema SensorInfo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SensorInfo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `SensorInfo` ;

-- -----------------------------------------------------
-- Table `air_quality_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `air_quality_sensor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `air_quality_sensor` (
  `id` INT NOT NULL,
  `tvoc` INT NOT NULL,
  `eco2` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `botIndex` INT NOT NULL,
  `latitude` DECIMAL(7,5) NOT NULL,
  `longitude` DECIMAL(8,5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `light_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `light_sensor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `light_sensor` (
  `id` INT NOT NULL,
  `lFull` INT NOT NULL,
  `lVis` INT NOT NULL,
  `lIR` INT NOT NULL,
  `lLux` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `botIndex` INT NOT NULL,
  `latitude` DECIMAL(7,5) NOT NULL,
  `longitude` DECIMAL(8,5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `power_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `power_sensor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `power_sensor` (
  `id` INT NOT NULL,
  `pb` INT NOT NULL,
  `vb` DECIMAL(7,2) NOT NULL,
  `ib` DECIMAL(7,2) NOT NULL,
  `pc` INT NOT NULL,
  `vc` DECIMAL(7,2) NOT NULL,
  `ic` DECIMAL(7,2) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `botIndex` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soil_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soil_sensor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soil_sensor` (
  `id` INT NOT NULL,
  `mSoil` INT NOT NULL,
  `tSoil` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `botIndex` INT NOT NULL,
  `latitude` DECIMAL(7,5) NOT NULL,
  `longitude` DECIMAL(8,5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `temp_hmd_pres_alt_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `temp_hmd_pres_alt_sensor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `temp_hmd_pres_alt_sensor` (
  `id` INT NOT NULL,
  `t` DECIMAL(4,1) NOT NULL,
  `p` INT NOT NULL,
  `a` INT NOT NULL,
  `h` DECIMAL(4,2) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `botIndex` INT NOT NULL,
  `latitude` DECIMAL(7,5) NOT NULL,
  `longitude` DECIMAL(8,5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
